WIP: Guideline to create a new protocol binding
w3c/wot-binding-templates pull request #104
Opened 2020-11-17 07:33 UTC by sebastiankb

also see #103

2020-11-17 12:43 UTC, egekorkan approved these changes

2020-11-17 12:44 UTC, egekorkan commented
Looks good to me, can be merged in the call tomorrow.

2020-11-18 08:51 UTC, relu91 requested changes
Just some minor typos. Other than that it looks ok!

2020-11-18 08:51 UTC, relu91 commented on index.html
> +        Please ensure that following information are provided and common shared:
*Please ensure that following information are provided and common shared* -> *Please ensure that the following information is provided and commonly shared*

2020-11-18 08:51 UTC, relu91 commented on index.html
> +        minimal requirements for information are required, which can then be used for distinct
a minimal -> minimal

2020-11-18 08:51 UTC, relu91 commented on index.html
> +          This includes that the <code>href</code> term of the <code>forms</code> container have to be used to encode the address information of the protocol for the
have -> has

2020-11-18 08:51 UTC, relu91 commented on index.html
> +        <li>Depending of the complexity of the protocol a corresponding and established context may be introduced within the <code>@context</code> to decleare all needed protocol features by correspo
decleare -> declare

2021-07-16 21:26 UTC, OhArthits approved these changes

2021-09-22 15:44 UTC, closed without merging