Adjust terminology usage in core document
w3c/wot-binding-templates pull request #197
Opened 2022-11-09 12:11 UTC by egekorkan

In #192 , I had added the new terminology items but I was not referring to them. In this PR, I am aligning the usage of the terminology for the core document.

2022-11-09 12:11 UTC, egekorkan commented on index.html
> +                Description[[WOT-THING-DESCRIPTION]] forms via reusable vocabulary and extensions.</li>
I have also added the mention of forms and data schemas

2022-11-10 16:25 UTC, relu91 requested changes
Two minor comments

2022-11-10 16:25 UTC, relu91 commented on index.html
> +             Description[[WOT-THING-DESCRIPTION] (TD), with Things that exhibit diverse protocols, payload formats and their usage.
```suggestion
             Description[[WOT-THING-DESCRIPTION]] (TD), with Things that exhibit diverse protocols, payload formats and their usage.
```
Syntax error?

2022-11-11 12:14 UTC, egekorkan commented
@relu91 regarding your comment saying "Even if you just added the correct naming, I'm wondering if we can also improve a little bit this sentence.", I am working on another PR that should fix this relationship problem of the documents: https://github.com/w3c/wot-binding-templates/pull/198

2022-11-16 15:33 UTC, merged